# Config for GPT model

training:
  train_ratio: 0.9
  manual_seed: 123
  batch_size: 2
  num_epochs: 5
  eval: # Evaluation settings during training
    freq: 10
    iter: 3
    start_context: "Every effort moves you" # Check example to see how model finishes this

model:
  tokenizer: "gpt2"
  vocab_size: 50257 # Vocabulary size
  context_length: 256 # Context length
  emb_dim: 768 # Embedding dimension
  n_heads: 12 # Number of attention heads
  n_layers: 12 # Number of layers
  drop_rate: 0.1 # Dropout rate
  qkv_bias: False # Query-Key-Value bias

# AdamW optimizer settings
optimizer:
  lr: 0.0004
  weight_decay: 0.1

